# Generated by rust2rpm 13
%bcond_without check
# Exa is not supposed to be used as a library
%global __cargo_skip_build 0
%global __cargo_is_lib() false

%global crate exa

Name:           rust-%{crate}
Version:        0.9.0
Release:        15%{?dist}
Summary:        Modern replacement for ls

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/exa
Source:         %{crates_source}
# Initial patched metadata
# * Bump to env_logger 0.7.1, https://github.com/ogham/exa/pull/603
# * Update git2 to 0.13, https://github.com/ogham/exa/pull/640
# * Update zoneinfo_compiled/datetime to 0.5, users to 0.10
#   https://github.com/ogham/exa/pull/667
Patch0:         exa-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
exa  is a modern replacement for the command-line program ls that ships
with Unix and Linux operating systems, with more features and better defaults.
It uses colours to distinguish file types and metadata.
It knows about symlinks, extended attributes, and Git. And it’s small, fast,
and just one single binary.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# MIT
# MIT or ASL 2.0
# MIT or ASL 2.0 or zlib
# Unlicense or MIT
License:        MIT

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENCE
%doc README.md
%{_bindir}/exa
%{_mandir}/man1/exa.1*
%dir %{_datadir}/bash-completion
%dir %{_datadir}/bash-completion/completions
%{_datadir}/bash-completion/completions/exa.bash
%dir %{_datadir}/fish
%dir %{_datadir}/fish/vendor_completions.d
%{_datadir}/fish/vendor_completions.d/exa.fish
%dir %{_datadir}/zsh
%dir %{_datadir}/zsh/site-functions
%{_datadir}/zsh/site-functions/_exa

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install
install -Dpm0644 -t %{buildroot}%{_mandir}/man1 contrib/man/exa.1
install -Dpm0644 -T contrib/completions.bash \
  %{buildroot}%{_datadir}/bash-completion/completions/exa.bash
install -Dpm0644 -T contrib/completions.fish \
  %{buildroot}%{_datadir}/fish/vendor_completions.d/exa.fish
install -Dpm0644 -T contrib/completions.zsh \
  %{buildroot}%{_datadir}/zsh/site-functions/_exa

%if %{with check}
%check
# https://github.com/ogham/exa/issues/318
%cargo_test || :
%endif

%changelog
* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.9.0-15
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Tue Dec 29 14:21:55 CET 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.9.0-14
- Rebuild against libgit2 1.1.x

* Sun Aug 16 15:01:23 GMT 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.9.0-13
- Rebuild

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.9.0-12
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Fri May 22 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.9.0-11
- Update users to 0.10

* Sun May 17 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.9.0-10
- Update zoneinfo_compiled/datetime to 0.5

* Wed Apr 15 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.9.0-9
- Rebuild for libgit2 1.0.0

* Thu Mar 19 11:33:52 CET 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.9.0-8
- Update git2 to 0.13

* Tue Mar 03 2020 Josh Stone <jistone@redhat.com> - 0.9.0-7
- Bump to git2 0.12

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.9.0-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Wed Dec 25 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.0-5
- Update git2 to 0.11

* Tue Dec 10 2019 Josh Stone <jistone@redhat.com> - 0.9.0-4
- Update git2 and env_logger deps

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.9.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sun Jul 21 18:29:00 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.0-2
- Correct fish completions directory

* Mon Jul 15 08:23:01 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.0-1
- Update to 0.9.0

* Sun Jul 14 19:34:42 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.0-17
- Regenerate

* Fri Jun 07 2019 Josh Stone <jistone@redhat.com> - 0.8.0-16
- Bump git2 to 0.9

* Tue May 07 14:00:28 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.0-15
- Update glob to 0.3, number_prefix to 0.3

* Thu Apr 25 17:20:22 CET 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0.8.0-214
- Rebuilt for rust-users 0.9.1

* Sun Feb 10 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.0-13
- Update git2 and env_logger deps

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.0-12
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Wed Nov 14 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.0-11
- Adapt to new packaging

* Fri Aug 10 2018 Josh Stone <jistone@redhat.com> - 0.8.0-10
- Rebuild with fixed rust-libgit2-sys-0.7.7

* Fri Aug 10 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.0-9
- Rebuild for libgit2 0.27.x

* Sat Jul 14 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.0-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Mon Jun 25 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.0-7
- Bump users to 0.7

* Mon Mar 26 2018 Josh Stone <jistone@redhat.com> - 0.8.0-6
- Bump ansi_term to 0.11

* Mon Mar 12 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.0-5
- Bump git2 to 0.7

* Fri Feb 09 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.0-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Mon Jan 08 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.0-3
- Rebuild for rust-packaging v5

* Thu Nov 30 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.0-2
- Bump lazy_static to 1

* Tue Nov 21 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.8.0-1
- Initial package
