#!/bin/sh
#
# SPDX-FileCopyrightText: Google Inc
# SPDX-FileCopyrightText: 2024 Vladimir Rusinov <vladimir.rusinov@gmail.com>
# SPDX-License-Identifier: Apache-2.0
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

set -e

# hadolint
if which docker 2> /dev/null ; then
	for f in $(find . -name Dockerfile); do
	    echo "=== Running hadolint on $f"
	    docker run --rm -i -v $(pwd)/.hadolint.yaml:/.config/hadolint.yaml ghcr.io/hadolint/hadolint < "${f}"
	done
else
	echo "WARN: docker is not installed"
fi
