# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate concolor-query

Name:           rust-concolor-query0.0.5
Version:        0.0.5
Release:        1%{?dist}
Summary:        Look up colored console capabilities

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/concolor-query
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Look up colored console capabilities.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+windows-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+windows-devel %{_description}

This package contains library source intended for building other packages which
use the "windows" feature of the "%{crate}" crate.

%files       -n %{name}+windows-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Jan 29 2024 Vladimir Rusinov <vladimir.rusinov@gmail.com> - 0.0.5-1
- Initial package
