# Generated by rust2rpm 24
%bcond_without check

%global crate snapbox

Name:           rust-snapbox
Version:        0.2.10
Release:        %autorelease
Summary:        Snapshot testing toolbox

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/snapbox
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Snapshot testing toolbox.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
# FIXME: no license files detected
%doc README.md
%{_bindir}/snap-fixture

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+backtrace-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+backtrace-devel %{_description}

This package contains library source intended for building other packages which
use the "backtrace" feature of the "%{crate}" crate.

%files       -n %{name}+backtrace-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cmd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cmd-devel %{_description}

This package contains library source intended for building other packages which
use the "cmd" feature of the "%{crate}" crate.

%files       -n %{name}+cmd-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+color-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+color-devel %{_description}

This package contains library source intended for building other packages which
use the "color" feature of the "%{crate}" crate.

%files       -n %{name}+color-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+color-auto-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+color-auto-devel %{_description}

This package contains library source intended for building other packages which
use the "color-auto" feature of the "%{crate}" crate.

%files       -n %{name}+color-auto-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+concolor-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+concolor-devel %{_description}

This package contains library source intended for building other packages which
use the "concolor" feature of the "%{crate}" crate.

%files       -n %{name}+concolor-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+content_inspector-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+content_inspector-devel %{_description}

This package contains library source intended for building other packages which
use the "content_inspector" feature of the "%{crate}" crate.

%files       -n %{name}+content_inspector-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debug-devel %{_description}

This package contains library source intended for building other packages which
use the "debug" feature of the "%{crate}" crate.

%files       -n %{name}+debug-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+detect-encoding-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+detect-encoding-devel %{_description}

This package contains library source intended for building other packages which
use the "detect-encoding" feature of the "%{crate}" crate.

%files       -n %{name}+detect-encoding-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+diff-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+diff-devel %{_description}

This package contains library source intended for building other packages which
use the "diff" feature of the "%{crate}" crate.

%files       -n %{name}+diff-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+document-features-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+document-features-devel %{_description}

This package contains library source intended for building other packages which
use the "document-features" feature of the "%{crate}" crate.

%files       -n %{name}+document-features-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dunce-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dunce-devel %{_description}

This package contains library source intended for building other packages which
use the "dunce" feature of the "%{crate}" crate.

%files       -n %{name}+dunce-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+filetime-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+filetime-devel %{_description}

This package contains library source intended for building other packages which
use the "filetime" feature of the "%{crate}" crate.

%files       -n %{name}+filetime-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+harness-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+harness-devel %{_description}

This package contains library source intended for building other packages which
use the "harness" feature of the "%{crate}" crate.

%files       -n %{name}+harness-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ignore-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ignore-devel %{_description}

This package contains library source intended for building other packages which
use the "ignore" feature of the "%{crate}" crate.

%files       -n %{name}+ignore-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libtest-mimic-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libtest-mimic-devel %{_description}

This package contains library source intended for building other packages which
use the "libtest-mimic" feature of the "%{crate}" crate.

%files       -n %{name}+libtest-mimic-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+os_pipe-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+os_pipe-devel %{_description}

This package contains library source intended for building other packages which
use the "os_pipe" feature of the "%{crate}" crate.

%files       -n %{name}+os_pipe-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+path-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+path-devel %{_description}

This package contains library source intended for building other packages which
use the "path" feature of the "%{crate}" crate.

%files       -n %{name}+path-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+similar-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+similar-devel %{_description}

This package contains library source intended for building other packages which
use the "similar" feature of the "%{crate}" crate.

%files       -n %{name}+similar-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tempfile-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tempfile-devel %{_description}

This package contains library source intended for building other packages which
use the "tempfile" feature of the "%{crate}" crate.

%files       -n %{name}+tempfile-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wait-timeout-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wait-timeout-devel %{_description}

This package contains library source intended for building other packages which
use the "wait-timeout" feature of the "%{crate}" crate.

%files       -n %{name}+wait-timeout-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+walkdir-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+walkdir-devel %{_description}

This package contains library source intended for building other packages which
use the "walkdir" feature of the "%{crate}" crate.

%files       -n %{name}+walkdir-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+yansi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+yansi-devel %{_description}

This package contains library source intended for building other packages which
use the "yansi" feature of the "%{crate}" crate.

%files       -n %{name}+yansi-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
