# Generated by rust2rpm 24
%bcond_without check
%global debug_package %{nil}

%global crate snapbox-macros

Name:           rust-snapbox-macros0.2
Version:        0.2.1
Release:        1%{?dist}
Summary:        Snapshot testing toolbox

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/snapbox-macros
#Source:         %{crates_source}
Source:         https://crates.io/api/v1/crates/%{crate}/%{version}/download#/%{crate}-%{version}.crate

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Snapshot testing toolbox.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debug-devel %{_description}

This package contains library source intended for building other packages which
use the "debug" feature of the "%{crate}" crate.

%files       -n %{name}+debug-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Oct 29 2023 Vladimir Rusinov <vladimir.rusinov@gmail.com> - 0.2.1-1
- Initial package
